title_book_link: "https://www.railstutorial.org/"
learn_enough_link: "https://www.learnenough.com/"
title_book_link_book: "https://www.railstutorial.org/book"
screencast_link: "https://screencasts.railstutorial.org/"
ror_help_page_link: "https://www.railstutorial.org/help"
contact_page_link: "https://www.railstutorial.org/contact"
michael_hart_link: "https://www.michaelhartl.com/"
news_link: "https://news.railstutorial.org/"
